version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php app.php'
  relay: pipes

otel:
  resource:
    service_name: "api-server"
    service_version: "${OTEL_SERVICE_VERSION:-1.0.0}"
    service_namespace: "${OTEL_SERVICE_NAMESPACE:-cash-track}"
    service_instance_id: "${OTEL_SERVICE_INSTANCE_ID:-UUID}"
  client: "${OTEL_EXPORTER_OTLP_CLIENT:-grpc}"
  insecure: "${OTEL_EXPORTER_OTLP_INSECURE:-true}"
  exporter: otlp
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT:-127.0.0.1:4317}"

http:
  address: 0.0.0.0:8080
  middleware:
    - http_metrics
    - gzip
    - otel
  pool:
    num_workers: ${RR_HTTP_NUM_WORKERS}
    supervisor:
      max_worker_memory: 100

kv:
  redis:
    driver: redis
    config:
      addrs:
        - ${REDIS_CONNECTION}

logs:
  mode: production
  level: info

metrics:
  address: 0.0.0.0:2112

jobs:
  pool:
    num_workers: 2
    max_worker_memory: 100
  consume:
    - high-priority
    - low-priority
  pipelines:
    high-priority:
      driver: memory
      config:
        priority: 1
    low-priority:
      driver: memory
      config:
        priority: 10
