version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php app.php'
  relay: pipes

http:
  address: 0.0.0.0:8080
  middleware:
    - http_metrics
    - gzip
  pool:
    num_workers: ${RR_HTTP_NUM_WORKERS}
    supervisor:
      max_worker_memory: 100

kv:
  redis:
    driver: redis
    config:
      addrs:
        - ${REDIS_CONNECTION}

logs:
  mode: production
  level: info

metrics:
  address: 0.0.0.0:2112

jobs:
  pool:
    num_workers: 2
    max_worker_memory: 100
  consume:
    - high-priority
    - low-priority
  pipelines:
    high-priority:
      driver: memory
      config:
        priority: 1
    low-priority:
      driver: memory
      config:
        priority: 10
