version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: 'php app.php'
  relay: pipes

http:
  address: 0.0.0.0:8080
  middleware:
    - gzip
    - http_metrics
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 100

kv:
  local:
    driver: memory
    config:
      interval: 60

logs:
  mode: production
  level: info

metrics:
  address: 0.0.0.0:2112

jobs:
  pool:
    num_workers: 2
    max_worker_memory: 100
  consume: {  }
