name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    uses: cash-track/.github/.github/workflows/build.yml@main
    with:
      image: cashtrack/api
    secrets: inherit
