name: build-base

on:
  workflow_dispatch:
  push:
    tags: ['base/v*']

permissions:
  contents: read
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    uses: cash-track/.github/.github/workflows/build.yml@main
    with:
      image: cashtrack/base-php
      dockerfile: ./base.Dockerfile
      tag_rules: |
        type=sha
        type=match,pattern=base/v(.*),group=1
    secrets: inherit
