name: Check

on:
  pull_request:
    branches:
      - master
      - rc*

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      DB_HOST: mysql:3306
      DB_NAME: cashtrack
      DB_USER: root
      DB_PASSWORD: secret

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: cashtrack
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: zip, mbstring, pdo_mysql, mysqli
          tools: composer, phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup application
        env:
          DB_HOST: mysql:${{ job.services.mysql.ports['3306'] }}
        run: |
          cp .env.actions .env
          composer install --no-progress --prefer-dist --optimize-autoloader
          php app.php encrypt:key -m .env
          php app.php configure -vv
          vendor/bin/spiral get-binary
          php app.php migrate:init
          php app.php migrate

      - name: Run tests
        env:
          DB_HOST: mysql:${{ job.services.mysql.ports['3306'] }}
        run: ./vendor/bin/phpunit
