name: quality

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality:
    uses: cash-track/.github/.github/workflows/quality-php.yml@main
    secrets: inherit
