name: release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    uses: cash-track/.github/.github/workflows/build.yml@main
    with:
      image: cashtrack/api
    secrets: inherit
  deploy:
    needs: build
    uses: cash-track/.github/.github/workflows/deploy.yml@main
    with:
      service: api
      post_deploy_cmds: 'php app.php migrate -s -n'
    secrets: inherit
