name: security

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Workspace
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Scan Packages For Vulnerability
        uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5  # v5
