name: security

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Security
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Setup Workspace
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan Packages For Vulnerability
        uses: symfonycorp/security-checker-action@v5
